Repository oslabs-beta/Zeus, pull requests merged in 2022-11, with the labels that each got.

#5 Aimee/changes
  .gitignore
  client/src/App.tsx
  client/src/index.tsx
  client/src/styles.css
  client/src/vite-env.d.ts
  index.html
  package-lock.json
  package.json
  tsconfig.json
  tsconfig.node.json
  vite.config.ts
  webpack.config.js
Labels: bug, enhancement

#21 Ed/frontend
  package-lock.json
  package.json
  public/assets/jarednom.png
  src/client/App.tsx
  src/client/Context.js
  src/client/Login/Login.js
  src/client/Login/__test__/Login.test.js
  src/client/MockData/mockData.js
  src/client/MockData/mockGeo.js
  src/client/components/BarChart.tsx
  src/client/components/GeographyChart.tsx
  src/client/components/Header.tsx
  src/client/components/LineChart.tsx
  src/client/components/PieChart.tsx
  src/client/components/ProgressCircle.tsx
  src/client/components/StatBox.tsx
  src/client/index.css
  src/client/index.html
  src/client/index.tsx
  src/client/interfaces.tsx
  src/client/notes.tsx
  src/client/scenes/bar/index.tsx
  src/client/scenes/calendar/__test__/calendar.test.js
  src/client/scenes/calendar/index.tsx
  src/client/scenes/contacts/index.tsx
  src/client/scenes/dashboard/index.tsx
  src/client/scenes/faq/index.tsx
  src/client/scenes/form/__test__/form.test.js
  src/client/scenes/form/index.tsx
  src/client/scenes/geography/index.tsx
  src/client/scenes/global/Sidebar.tsx
  src/client/scenes/global/Topbar.tsx
  src/client/scenes/global/__test__/Topbar.test.js
  src/client/scenes/invoices/index.tsx
  src/client/scenes/line/index.tsx
  src/client/scenes/pie/index.tsx
  src/client/scenes/team/index.tsx
  src/client/theme.tsx
  webpack.config.js
Labels: enhancement

#22 Revert "Ed/frontend"
  package-lock.json
  package.json
  public/assets/jarednom.png
  src/client/App.tsx
  src/client/Context.js
  src/client/Login/Login.js
  src/client/Login/__test__/Login.test.js
  src/client/MockData/mockData.js
  src/client/MockData/mockGeo.js
  src/client/components/BarChart.tsx
  src/client/components/GeographyChart.tsx
  src/client/components/Header.tsx
  src/client/components/LineChart.tsx
  src/client/components/PieChart.tsx
  src/client/components/ProgressCircle.tsx
  src/client/components/StatBox.tsx
  src/client/index.css
  src/client/index.html
  src/client/index.tsx
  src/client/interfaces.tsx
  src/client/notes.tsx
  src/client/scenes/bar/index.tsx
  src/client/scenes/calendar/__test__/calendar.test.js
  src/client/scenes/calendar/index.tsx
  src/client/scenes/contacts/index.tsx
  src/client/scenes/dashboard/index.tsx
  src/client/scenes/faq/index.tsx
  src/client/scenes/form/__test__/form.test.js
  src/client/scenes/form/index.tsx
  src/client/scenes/geography/index.tsx
  src/client/scenes/global/Sidebar.tsx
  src/client/scenes/global/Topbar.tsx
  src/client/scenes/global/__test__/Topbar.test.js
  src/client/scenes/invoices/index.tsx
  src/client/scenes/line/index.tsx
  src/client/scenes/pie/index.tsx
  src/client/scenes/team/index.tsx
  src/client/theme.tsx
  webpack.config.js
Labels: bug, invalid

#23 Aimee/backend
  .d.ts
  .vscode/settings.json
  dist/src/client/Dashboard.js
  dist/src/client/Pod.js
  dist/src/server/middleware.js
  dist/src/server/server.js
  dist/webpack.config.js
  package-lock.json
  package.json
  src/client/Dashboard.tsx
  src/client/Pod.tsx
  src/server/middleware.ts
  src/server/server.ts
  test.html
  tsconfig.json
  webpack.config.js
Labels: enhancement

#26 Visualizer in progress...
  .d.ts
  dist/src/client/Dashboard.js
  package-lock.json
  package.json
  src/client/Dashboard.tsx
  src/client/index.html
Labels: enhancement, help wanted

#56 updated frontend codebase, added styling
  package-lock.json
  package.json
  src/client/App.tsx
  src/client/Context.jsx
  src/client/Login.jsx
  src/client/Yaku.png
  src/client/assets/IMG_4957.png
  src/client/index.html
  src/client/index.tsx
  src/client/styles.css
  webpack.config.js
Labels: enhancement

#57 Aimee/frontend
  dist/src/client/App.js
  dist/src/client/Context.js
  dist/src/client/Dashboard.js
  dist/src/client/Login.js
  dist/src/client/components/Chart.js
  dist/src/client/components/GUI.js
  dist/src/client/components/Header.js
  dist/src/client/components/Main.js
  dist/src/client/components/Sidebar.js
  dist/src/client/index.js
  dist/src/client/new.js
  dist/webpack.config.js
  package-lock.json
  package.json
  src/client/App.tsx
  src/client/Dashboard.tsx
  src/client/index.html
Labels: bug, enhancement
