Repository oslabs-beta/Zeus, pull requests merged in 2022-12, with the labels that each got.

#90 Aimee/backend
  .gitignore
  manifests/prometheus-alertmanager.yaml
  manifests/prometheus-operator.yaml
  manifests/prometheus-secret.yaml
  package-lock.json
  package.json
  src/server/controllers/userController.ts
  src/server/database/db.ts
  src/server/server.ts
Labels: bug, enhancement

#93 MongoDB working.
  src/server/database/db.js
Labels: enhancement

#95 Aimee/backend
  src/server/database/db.ts
  src/server/server.ts
Labels: enhancement

#97 removed some required value for schema
  src/server/controllers/userController.ts
  src/server/database/db.ts
Labels: bug, enhancement

#102 Grabing health metrics from CLI
  src/server/middleware.ts
Labels: enhancement

#105 Created Files and Added more Logic to backend
  .eslintrc.json
  CODE_OF_CONDUCT.md
  CONTRIBUTING.md
  package-lock.json
  package.json
  src/server/Interfaces/example.ts
  src/server/controllers/userController.ts
  src/server/database/db.ts
  src/server/middleware.ts
  src/server/server.ts
Labels: documentation, enhancement

#106 Ed/frontend
  src/client/App.tsx
  src/client/components/CustomDash.tsx
  src/client/components/Faq.tsx
  src/client/components/GrafanaDash.tsx
  src/client/components/Header.tsx
  src/client/components/Kluster.tsx
  src/client/components/VisD3.tsx
  src/client/interfaces/index.ts
  src/client/styles.css
Labels: enhancement

#108 Resolving merge conflicts from testing branch to backend branch
  dist/bundle.js
  dist/bundle.js.LICENSE.txt
  dist/index.html
  dist/src/server/middleware.js
  dist/src/server/server.js
  dist/webpack.config.js
  manifests/additional-configs/additional-scrape-configs.yaml
  manifests/additional-configs/prometheus-additional-configs.yaml
  manifests/patch.json
  package-lock.json
  package.json
  src/server/controllers/cookieController.ts
  src/server/controllers/sessionController.ts
  src/server/database/sessionModel.ts
Labels: bug

#110 Testing user middleware
  __test__/databaseConnection.test.ts
  __test__/userController.test.ts
  package-lock.json
  package.json
Labels: enhancement

#112 Removed duplicated files and replaced iframe link
  manifests/metric server/metricsServer-components/autoscale/kustomization.yaml
  manifests/metric server/metricsServer-components/autoscale/patch.yaml
  manifests/metric server/metricsServer-components/autoscale/rbac.yaml
  manifests/metric server/metricsServer-components/high-availability-1.21+/kustomization.yaml
  manifests/metric server/metricsServer-components/high-availability-1.21+/patch-pdb-version.yaml
  manifests/metric server/metricsServer-components/high-availability/kustomization.yaml
  manifests/metric server/metricsServer-components/high-availability/patch.yaml
  manifests/metric server/metricsServer-components/high-availability/pdb.yaml
  manifests/metric server/metricsServer-components/release/kustomization.yaml
  manifests/metric server/metricsServer-components/test/kustomization.yaml
  manifests/metric server/metricsServer-overlays/release-ha-1.21+/kustomization.yaml
  manifests/metric server/metricsServer-overlays/release-ha/kustomization.yaml
  manifests/metric server/metricsServer-overlays/release/kustomization.yaml
  manifests/metric server/metricsServer-overlays/test-ha/kustomization.yaml
  manifests/metric server/metricsServer-overlays/test/kustomization.yaml
  src/client/components/Faq.tsx
  src/client/components/GrafanaDash.tsx
  src/server/database/sessionModel.ts
Labels: enhancement

#115 Aimee/frontend
  README.md
  src/client/components/GrafanaDash.tsx
Labels: bug

#114 Created README -1st Draft
  src/client/components/GrafanaDash.tsx
Labels: documentation
